### ISSUE TITLE
NamedTemporaryFile() got an unexpected keyword argument 'delete_on_close'

### ISSUE THREAD

**Issue by mogupta** [niknah/ComfyUI-F5-TTS#1]
2024-10-24 02:17:22,719 - root - INFO - To see the GUI go to: http://127.0.0.1:18188
2024-10-24 02:20:48,869 - root - INFO - got prompt
2024-10-24 02:20:48,873 - root - WARNING - WARNING: Strings must be encoded before hashing
2024-10-24 02:24:38,865 - jieba - DEBUG - Building prefix dict from the default dictionary ...
2024-10-24 02:24:39,497 - jieba - DEBUG - Dumping model to file cache /tmp/jieba.cache
2024-10-24 02:24:39,557 - jieba - DEBUG - Loading model cost 0.692 seconds.
2024-10-24 02:24:39,557 - jieba - DEBUG - Prefix dict has been built successfully.
2024-10-24 02:24:45,382 - root - ERROR - !!! Exception during processing !!! NamedTemporaryFile() got an unexpected keyword argument 'delete_on_close'
2024-10-24 02:24:45,383 - root - ERROR - Traceback (most recent call last):
  File "/workspace/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/workspace/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/workspace/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/workspace/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-F5-TTS/F5TTS.py", line 172, in create
    audio = self.generate_audio(voices, model_obj, speech)
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-F5-TTS/F5TTS.py", line 137, in generate_audio
    wave_file = tempfile.NamedTemporaryFile(suffix=".wav", delete_on_close=False)
TypeError: NamedTemporaryFile() got an unexpected keyword argument 'delete_on_close'

2024-10-24 02:24:45,384 - root - INFO - Prompt executed in 236.51 seconds

**Comment by niknah** [comment]
Can you pull the latest or reinstall.
That was a python 3.12 option, I have changed it.

**Comment by mogupta** [comment]
The default speed is very slow. how can we increase it ?

**Comment by niknah** [comment]
It's quite quick for me.  Using your own voice or the one from the examples?

**Comment by mogupta** [comment]
What I mean is we should have a speed widget inside the node like https://github.com/AIFSH/F5-TTS-ComfyUI 
We can adjust the speech speed . but this node is not working.

**Comment by niknah** [comment]
I'm thinking this could be in another custom_node so that other audios can use it.

Check the sample rate of the audio that you are using.  Also check to see if you have the same problem with the example audios  https://github.com/niknah/ComfyUI-F5-TTS/tree/main/examples

Try speeding up the audio that you are using, see if that helps.

**Comment by niknah** [comment]
I had a little look at this.  Update / reinstall it now.  I changed something with where it was getting the sample rate from
