### ISSUE TITLE
 [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by pandalay1** [niknah/ComfyUI-F5-TTS#11]
WARNING: F5TTSAudioInputs.IS_CHANGED() got an unexpected keyword argument 'model'
Converting audio...
F5TTS: Cannot remove? C:\Users\****\AppData\Local\Temp\tmpkzgpj26j.wav
[WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\****\\AppData\\Local\\Temp\\tmpkzgpj26j.wav'
!!! Exception during processing !!! [WinError 2] The system cannot find the file specified

**Comment by pandalay1** [comment]
No, generation stops after this error. Full log below.

got prompt
WARNING: F5TTSAudioInputs.IS_CHANGED() got an unexpected keyword argument 'model'
Converting audio...
F5TTS: Cannot remove? C:\Users\panda\AppData\Local\Temp\tmprl15676t.wav
[WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\panda\\AppData\\Local\\Temp\\tmprl15676t.wav'
!!! Exception during processing !!! [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-F5-TTS\F5TTS.py", line 210, in create
    main_voice = self.load_voice_from_input(sample_audio, sample_text)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-F5-TTS\F5TTS.py", line 196, in load_voice_from_input
    r = F5TTSCreate.load_voice(self.wave_file.name, sample_text)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-F5-TTS\F5TTS.py", line 53, in load_voice
    main_voice["ref_audio"], main_voice["ref_text"] = preprocess_ref_audio_text( # noqa E501
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-F5-TTS\F5-TTS\model\utils_infer.py", line 146, in preprocess_ref_audio_text
    aseg = AudioSegment.from_file(ref_audio_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nightly_pytorch\python_embeded\Lib\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nightly_pytorch\python_embeded\Lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "subprocess.py", line 1026, in __init__
  File "subprocess.py", line 1538, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

Prompt executed in 0.05 seconds

**Comment by niknah** [comment]
It might not have made the audio from the input.  I have put an error message there.  Can you update it and run it again.  Where which node does the sample audio input come from and can you play it in "preview audio"

**Comment by niknah** [comment]
I think I've fixed this in a recent update.  Tell me if you're still getting this problem.
