### ISSUE TITLE
Audio output file has no sound (it's silent). Also Whisper FileNotFoundError.

### ISSUE THREAD

**Issue by boryxz** [niknah/ComfyUI-F5-TTS#16]
Hello!

When I'm using the simple_ComfyUI_F5TTS_workflow.json > Audio output file generated has no sound (it's silent).
I put the F5TTS_test_en_1_ref_short.wav and F5TTS_test_en_1_ref_short.txt in the input folder.

Also when using the F5TTS_whisper_workflow.json > I get FileNotFoundError.

==========
Log for the simple workflow:

D:\DEV\AI\ComfyUI\portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-16 11:30:12.569865
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: D:\DEV\AI\ComfyUI\portable\python_embeded\python.exe
** ComfyUI Path: D:\DEV\AI\ComfyUI\portable\ComfyUI
** Log path: D:\DEV\AI\ComfyUI\portable\comfyui.log

Prestartup times for custom nodes:
   3.0 seconds: D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 6144 MB, total RAM 16329 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1660 Ti : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: D:\DEV\AI\ComfyUI\portable\ComfyUI\web
Building prefix dict from the default dictionary ...
Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\CC\AppData\Local\Temp\jieba.cache
Loading model from cache C:\Users\CC\AppData\Local\Temp\jieba.cache
Loading model cost 0.619 seconds.
Loading model cost 0.619 seconds.
Prefix dict has been built successfully.
Prefix dict has been built successfully.
Word segmentation module jieba initialized.

PyTorch version 2.5.1+cu124 available.
D:\DEV\AI\ComfyUI\portable\python_embeded\Lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
### ComfyUI Revision: 2890 [9a616b81] *DETACHED | Released on '2024-12-04'

Import times for custom nodes:
   0.0 seconds: D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\ComfyUI-Whisper
   0.5 seconds: D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\ComfyUI-Manager
   3.5 seconds: D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\ComfyUI-F5-TTS

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
got prompt
WARNING: Strings must be encoded before hashing
audio_text
Some call me nature, others call me mother nature.

Converting audio...
Using custom reference text...

ref_text   Some call me nature, others call me mother nature.
.
Download Vocos from huggingface charactr/vocos-mel-24khz

vocab :  D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\ComfyUI-F5-TTS\F5-TTS\data/Emilia_ZH_EN_pinyin/vocab.txt
token :  custom
model :  C:\Users\CC\.cache\huggingface\hub\models--SWivid--F5-TTS\snapshots\4dcc16f297f2ff98a17b3726b16f5de5a5e45672\F5TTS_Base\model_1200000.safetensors

No voice tag found, using main.
Voice: main
text:Hello World this is the end
gen_text 0 Hello World this is the end

Generating audio in 1 batches...
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:33<00:00, 33.87s/it]
Prompt executed in 58.85 seconds

==================
Log for the whisper workflow:

# ComfyUI Error Report
## Error Details
- **Node ID:** 13
- **Node Type:** Apply Whisper
- **Exception Type:** FileNotFoundError
- **Exception Message:** [WinError 2] The system cannot find the file specified
## Stack Trace
```
  File "D:\DEV\AI\ComfyUI\portable\ComfyUI\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\DEV\AI\ComfyUI\portable\ComfyUI\execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\DEV\AI\ComfyUI\portable\ComfyUI\execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\DEV\AI\ComfyUI\portable\ComfyUI\execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\ComfyUI-Whisper\apply_whisper.py", line 34, in apply_whisper
    result = model.transcribe(audio_save_path, word_timestamps=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\DEV\AI\ComfyUI\portable\python_embeded\Lib\site-packages\whisper\transcribe.py", line 133, in transcribe
    mel = log_mel_spectrogram(audio, model.dims.n_mels, padding=N_SAMPLES)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\DEV\AI\ComfyUI\portable\python_embeded\Lib\site-packages\whisper\audio.py", line 140, in log_mel_spectrogram
    audio = load_audio(audio)
            ^^^^^^^^^^^^^^^^^

  File "D:\DEV\AI\ComfyUI\portable\python_embeded\Lib\site-packages\whisper\audio.py", line 58, in load_audio
    out = run(cmd, capture_output=True, check=True).stdout
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "subprocess.py", line 548, in run

  File "subprocess.py", line 1026, in __init__

  File "subprocess.py", line 1538, in _execute_child

```
## System Information
- **ComfyUI Version:** v0.3.7
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.5.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce GTX 1660 Ti : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 6441992192
  - **VRAM Free:** 5087418368
  - **Torch VRAM Total:** 469762048
  - **Torch VRAM Free:** 201054208

## Logs
```
2024-12-16T11:48:44.319459 - [START] Security scan2024-12-16T11:48:44.319459 - 
2024-12-16T11:48:48.422951 - [DONE] Security scan2024-12-16T11:48:48.422951 - 
2024-12-16T11:48:48.574629 - ## ComfyUI-Manager: installing dependencies done.2024-12-16T11:48:48.574629 - 
2024-12-16T11:48:48.574629 - ** ComfyUI startup time:2024-12-16T11:48:48.574629 -  2024-12-16T11:48:48.574629 - 2024-12-16 11:48:48.5746292024-12-16T11:48:48.574629 - 
2024-12-16T11:48:48.626169 - ** Platform:2024-12-16T11:48:48.626169 -  2024-12-16T11:48:48.626169 - Windows2024-12-16T11:48:48.626169 - 
2024-12-16T11:48:48.627169 - ** Python version:2024-12-16T11:48:48.627169 -  2024-12-16T11:48:48.627169 - 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]2024-12-16T11:48:48.627169 - 
2024-12-16T11:48:48.627169 - ** Python executable:2024-12-16T11:48:48.627169 -  2024-12-16T11:48:48.627169 - D:\DEV\AI\ComfyUI\portable\python_embeded\python.exe2024-12-16T11:48:48.627169 - 
2024-12-16T11:48:48.627169 - ** ComfyUI Path:2024-12-16T11:48:48.627169 -  2024-12-16T11:48:48.627169 - D:\DEV\AI\ComfyUI\portable\ComfyUI2024-12-16T11:48:48.627169 - 
2024-12-16T11:48:48.627169 - ** Log path:2024-12-16T11:48:48.627169 -  2024-12-16T11:48:48.627169 - D:\DEV\AI\ComfyUI\portable\comfyui.log2024-12-16T11:48:48.628169 - 
2024-12-16T11:48:50.067035 - 
Prestartup times for custom nodes:2024-12-16T11:48:50.067035 - 
2024-12-16T11:48:50.068035 -    5.8 seconds:2024-12-16T11:48:50.068035 -  2024-12-16T11:48:50.068472 - D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\ComfyUI-Manager2024-12-16T11:48:50.068472 - 
2024-12-16T11:48:50.068472 - 
2024-12-16T11:49:21.071382 - Total VRAM 6144 MB, total RAM 16329 MB
2024-12-16T11:49:21.072383 - pytorch version: 2.5.1+cu124
2024-12-16T11:49:21.080480 - Set vram state to: NORMAL_VRAM
2024-12-16T11:49:21.080480 - Device: cuda:0 NVIDIA GeForce GTX 1660 Ti : cudaMallocAsync
2024-12-16T11:49:22.916389 - Using pytorch cross attention
2024-12-16T11:49:29.518224 - [Prompt Server] web root: D:\DEV\AI\ComfyUI\portable\ComfyUI\web
2024-12-16T11:49:32.877444 - Building prefix dict from the default dictionary ...
2024-12-16T11:49:32.877444 - Building prefix dict from the default dictionary ...
2024-12-16T11:49:32.877444 - Loading model from cache C:\Users\CC\AppData\Local\Temp\jieba.cache
2024-12-16T11:49:32.877444 - Loading model from cache C:\Users\CC\AppData\Local\Temp\jieba.cache
2024-12-16T11:49:33.530069 - Loading model cost 0.653 seconds.
2024-12-16T11:49:33.530961 - Loading model cost 0.653 seconds.
2024-12-16T11:49:33.530961 - Prefix dict has been built successfully.
2024-12-16T11:49:33.530961 - Prefix dict has been built successfully.
2024-12-16T11:49:33.530961 - Word segmentation module jieba initialized.
2024-12-16T11:49:33.530961 - 
2024-12-16T11:49:36.578261 - PyTorch version 2.5.1+cu124 available.
2024-12-16T11:49:38.084336 - D:\DEV\AI\ComfyUI\portable\python_embeded\Lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
2024-12-16T11:49:38.985943 - ### Loading: ComfyUI-Manager (V2.55.5)2024-12-16T11:49:38.986977 - 
2024-12-16T11:49:39.132373 - ### ComfyUI Revision: 2890 [9a616b81] *DETACHED | Released on '2024-12-04'2024-12-16T11:49:39.132373 - 
2024-12-16T11:49:39.585633 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json2024-12-16T11:49:39.585633 - 
2024-12-16T11:49:39.634241 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json2024-12-16T11:49:39.634241 - 
2024-12-16T11:49:39.644339 - 
Import times for custom nodes:
2024-12-16T11:49:39.644339 -    0.0 seconds: D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-12-16T11:49:39.645339 -    0.0 seconds: D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\ComfyUI_essentials
2024-12-16T11:49:39.646468 -    0.2 seconds: D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\ComfyUI-Whisper
2024-12-16T11:49:39.646468 -    0.5 seconds: D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-12-16T11:49:39.647468 -    8.0 seconds: D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\ComfyUI-F5-TTS
2024-12-16T11:49:39.647468 - 
2024-12-16T11:49:39.654474 - Starting server

2024-12-16T11:49:39.654474 - To see the GUI go to: http://127.0.0.1:8188
2024-12-16T11:49:39.725126 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json2024-12-16T11:49:39.728320 - 
2024-12-16T11:49:39.830216 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json2024-12-16T11:49:39.830216 - 
2024-12-16T11:49:39.866713 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2024-12-16T11:49:39.867713 - 
2024-12-16T11:49:41.463122 - FETCH DATA from: D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json2024-12-16T11:49:41.463122 - 2024-12-16T11:49:41.473214 -  [DONE]2024-12-16T11:49:41.473214 - 
2024-12-16T11:49:50.442560 - got prompt
2024-12-16T11:49:50.445563 - WARNING: object supporting the buffer API required
2024-12-16T11:49:50.682926 - D:\DEV\AI\ComfyUI\portable\python_embeded\Lib\site-packages\whisper\__init__.py:150: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(fp, map_location=device)
2024-12-16T11:49:51.700753 - !!! Exception during processing !!! [WinError 2] The system cannot find the file specified
2024-12-16T11:49:51.702755 - Traceback (most recent call last):
  File "D:\DEV\AI\ComfyUI\portable\ComfyUI\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DEV\AI\ComfyUI\portable\ComfyUI\execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DEV\AI\ComfyUI\portable\ComfyUI\execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\DEV\AI\ComfyUI\portable\ComfyUI\execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\ComfyUI-Whisper\apply_whisper.py", line 34, in apply_whisper
    result = model.transcribe(audio_save_path, word_timestamps=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DEV\AI\ComfyUI\portable\python_embeded\Lib\site-packages\whisper\transcribe.py", line 133, in transcribe
    mel = log_mel_spectrogram(audio, model.dims.n_mels, padding=N_SAMPLES)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DEV\AI\ComfyUI\portable\python_embeded\Lib\site-packages\whisper\audio.py", line 140, in log_mel_spectrogram
    audio = load_audio(audio)
            ^^^^^^^^^^^^^^^^^
  File "D:\DEV\AI\ComfyUI\portable\python_embeded\Lib\site-packages\whisper\audio.py", line 58, in load_audio
    out = run(cmd, capture_output=True, check=True).stdout
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "subprocess.py", line 548, in run
  File "subprocess.py", line 1026, in __init__
  File "subprocess.py", line 1538, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

2024-12-16T11:49:51.704757 - Prompt executed in 1.26 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":14,"last_link_id":7,"nodes":[{"id":12,"type":"F5TTSAudioInputs","pos":[1025,155],"size":[400,200],"flags":{},"order":2,"mode":0,"inputs":[{"name":"sample_audio","type":"AUDIO","link":3},{"name":"sample_text","type":"STRING","link":5,"widget":{"name":"sample_text"}}],"outputs":[{"name":"AUDIO","type":"AUDIO","links":[4],"slot_index":0}],"properties":{"Node name for S&R":"F5TTSAudioInputs"},"widgets_values":["Text of sample_audio","This is what I want to say",374,"randomize","F5"]},{"id":4,"type":"LoadAudio","pos":[241,146],"size":[315,124],"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"AUDIO","type":"AUDIO","links":[3,6],"slot_index":0}],"properties":{"Node name for S&R":"LoadAudio"},"widgets_values":["F5TTS_test_en_1_ref_short.wav",null,""]},{"id":13,"type":"Apply Whisper","pos":[618,249],"size":[315,98],"flags":{},"order":1,"mode":0,"inputs":[{"name":"audio","type":"AUDIO","link":6}],"outputs":[{"name":"text","type":"STRING","links":[5,7],"slot_index":0},{"name":"segments_alignment","type":"whisper_alignment","links":null},{"name":"words_alignment","type":"whisper_alignment","links":null}],"properties":{"Node name for S&R":"Apply Whisper"},"widgets_values":["base"]},{"id":14,"type":"DisplayAny","pos":[651,451],"size":[315,100],"flags":{},"order":3,"mode":0,"inputs":[{"name":"input","type":"*","link":7}],"outputs":[{"name":"STRING","type":"STRING","links":null}],"properties":{"Node name for S&R":"DisplayAny"},"widgets_values":["raw value"]},{"id":2,"type":"PreviewAudio","pos":[1043,450],"size":[315,76],"flags":{},"order":4,"mode":0,"inputs":[{"name":"audio","type":"AUDIO","link":4}],"outputs":[],"properties":{"Node name for S&R":"PreviewAudio"},"widgets_values":[null]}],"links":[[3,4,0,12,0,"AUDIO"],[4,12,0,2,0,"AUDIO"],[5,13,0,12,1,"STRING"],[6,4,0,13,0,"AUDIO"],[7,13,0,14,0,"*"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.9229599817706635,"offset":[-155.27354303916528,101.90166373970601]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

===============

Thank you!

**Comment by niknah** [comment]
Need to install ffmpeg for whisper to work.
https://www.gyan.dev/ffmpeg/builds/
`winget install "FFmpeg (Essentials Build)"`

Then restart ComfyUI

**Comment by boryxz** [comment]
I've installed ffmpeg, now there is no error when using whisper workflow. But the generated file is still silent, there is no sound.

D:\DEV\AI\ComfyUI\portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-16 15:44:42.007453
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: D:\DEV\AI\ComfyUI\portable\python_embeded\python.exe
** ComfyUI Path: D:\DEV\AI\ComfyUI\portable\ComfyUI
** Log path: D:\DEV\AI\ComfyUI\portable\comfyui.log

Prestartup times for custom nodes:
   4.4 seconds: D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 6144 MB, total RAM 16329 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1660 Ti : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: D:\DEV\AI\ComfyUI\portable\ComfyUI\web
Building prefix dict from the default dictionary ...
Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\CC\AppData\Local\Temp\jieba.cache
Loading model from cache C:\Users\CC\AppData\Local\Temp\jieba.cache
Loading model cost 0.618 seconds.
Loading model cost 0.618 seconds.
Prefix dict has been built successfully.
Prefix dict has been built successfully.
Word segmentation module jieba initialized.

PyTorch version 2.5.1+cu124 available.
### Loading: ComfyUI-Manager (V2.55.5)
### ComfyUI Revision: 2890 [9a616b81] *DETACHED | Released on '2024-12-04'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json

Import times for custom nodes:
   0.0 seconds: D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.2 seconds: D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\ComfyUI-Whisper
   0.3 seconds: D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.7 seconds: D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\ComfyUI-Manager
  26.8 seconds: D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\ComfyUI-F5-TTS

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
got prompt
WARNING: object supporting the buffer API required
D:\DEV\AI\ComfyUI\portable\python_embeded\Lib\site-packages\whisper\__init__.py:150: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(fp, map_location=device)
D:\DEV\AI\ComfyUI\portable\python_embeded\Lib\site-packages\whisper\timing.py:42: UserWarning: Failed to launch Triton kernels, likely due to missing CUDA toolkit; falling back to a slower median kernel implementation...
  warnings.warn(
D:\DEV\AI\ComfyUI\portable\python_embeded\Lib\site-packages\whisper\timing.py:146: UserWarning: Failed to launch Triton kernels, likely due to missing CUDA toolkit; falling back to a slower DTW implementation...
  warnings.warn(
Converting audio...
Using custom reference text...

ref_text   Some call me nature. Others call me Mother Nature.
Download Vocos from huggingface charactr/vocos-mel-24khz

vocab :  D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\ComfyUI-F5-TTS\F5-TTS\data/Emilia_ZH_EN_pinyin/vocab.txt
token :  custom
model :  C:\Users\CC\.cache\huggingface\hub\models--SWivid--F5-TTS\snapshots\4dcc16f297f2ff98a17b3726b16f5de5a5e45672\F5TTS_Base\model_1200000.safetensors

No voice tag found, using main.
Voice: main
text:This is what I want to say
gen_text 0 This is what I want to say


Generating audio in 1 batches...
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:37<00:00, 37.19s/it]
Prompt executed in 59.53 seconds

**Comment by niknah** [comment]
simple_ComfyUI_F5TTS_workflow.json  doesn't depend on whisper.  You may be using another workflow.

No audio as in there is no play button?  Or the play button plays silence?

**Comment by boryxz** [comment]
I understand that simple_ComfyUI_F5TTS_workflow.json doesn't use Whisper. 

Both workflows simple_ComfyUI_F5TTS_workflow.json and F5TTS_whisper_workflow.json generate a file with no sound.
It "plays", has more or less number of seconds depending if the text is shorter or longer, but it's silent. I can hear a little static noise at the beggining and at the end of the file.


D:\DEV\AI\ComfyUI\portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-17 10:18:56.455566
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: D:\DEV\AI\ComfyUI\portable\python_embeded\python.exe
** ComfyUI Path: D:\DEV\AI\ComfyUI\portable\ComfyUI
** Log path: D:\DEV\AI\ComfyUI\portable\comfyui.log

Prestartup times for custom nodes:
   3.0 seconds: D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 6144 MB, total RAM 16329 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1660 Ti : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: D:\DEV\AI\ComfyUI\portable\ComfyUI\web
Building prefix dict from the default dictionary ...
Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\CC\AppData\Local\Temp\jieba.cache
Loading model from cache C:\Users\CC\AppData\Local\Temp\jieba.cache
Loading model cost 0.613 seconds.
Loading model cost 0.613 seconds.
Prefix dict has been built successfully.
Prefix dict has been built successfully.
Word segmentation module jieba initialized.

PyTorch version 2.5.1+cu124 available.
### Loading: ComfyUI-Manager (V2.55.5)
### ComfyUI Revision: 2890 [9a616b81] *DETACHED | Released on '2024-12-04'

Import times for custom nodes:
   0.0 seconds: D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\ComfyUI-Whisper
   0.5 seconds: D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\ComfyUI-Manager
   3.2 seconds: D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\ComfyUI-F5-TTS

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
got prompt
WARNING: Strings must be encoded before hashing
audio_text
Some call me nature, others call me mother nature.

Converting audio...
Using custom reference text...

ref_text   Some call me nature, others call me mother nature.
.
Download Vocos from huggingface charactr/vocos-mel-24khz

vocab :  D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\ComfyUI-F5-TTS\F5-TTS\data/Emilia_ZH_EN_pinyin/vocab.txt
token :  custom
model :  C:\Users\CC\.cache\huggingface\hub\models--SWivid--F5-TTS\snapshots\4dcc16f297f2ff98a17b3726b16f5de5a5e45672\F5TTS_Base\model_1200000.safetensors

No voice tag found, using main.
Voice: main
text:Hello World this is the end
gen_text 0 Hello World this is the end


Generating audio in 1 batches...
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:40<00:00, 40.26s/it]
Prompt executed in 46.95 seconds

![simple workflow](https://github.com/user-attachments/assets/fccf6897-2c40-431e-9ec4-77fab226ded1)
![comfyui_f5_tts](https://github.com/user-attachments/assets/2aecdca8-8b81-4a15-a2eb-18a9889ed6ff)

**Comment by boryxz** [comment]
It's working now!

also posted here for help:

https://github.com/SWivid/F5-TTS/issues/637

D:\DEV\AI\ComfyUI\portable\ComfyUI\custom_nodes\ComfyUI-F5-TTS\F5-TTS\src\f5_tts\infer

edited the utils_infer.py file.

![utils_infer py](https://github.com/user-attachments/assets/e8b8b3f7-62ae-467b-9ccf-bb07763636e5)


Thank you!

**Comment by niknah** [comment]
Thanks.  Do you know what causes a need for float32?

**Comment by boryxz** [comment]
I'm not sure. Maybe my gtx 1660 ti is too old...
